//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LecturasRestAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medidor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medidor()
        {
            this.Lecturas = new HashSet<Lectura>();
        }
    
        public int Id { get; set; }
        public int ModeloId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.Data.Entity.Spatial.DbGeography GeoLocalizacion { get; set; }
        public Nullable<int> UltimaLecturaId { get; set; }
        public string Domicilio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lectura> Lecturas { get; set; }
        public virtual Lectura UltimaLectura { get; set; }
        public virtual ModeloDeMedidor ModeloDeMedidor { get; set; }
    }
}
